Complete index page
JordanWheelerDev/resumify pull request #1
Opened 2024-05-25 17:38 UTC by JordanWheelerDev

- Added a "How Resumify Works" section
- Added full page screenshots for the templates.

2024-05-26 12:06 UTC, chadmroberts88 requested changes

2024-05-26 12:06 UTC, chadmroberts88 commented on img/templates/fancy-blue.png
You probably don't need to include the "Build Your Resume" sidebar in your images here, since the user would be more interested in the look of the template when choosing one to select.

2024-05-26 14:25 UTC, JordanWheelerDev commented on img/templates/fancy-blue.png
Updated the images to remove the sidebar in the image previews.

2024-05-28 19:42 UTC, chadmroberts88 commented on img/templates/fancy-blue.png
Did you push these changes? I don't see them here.

2024-05-31 21:49 UTC, JordanWheelerDev commented on img/templates/fancy-blue.png
Sorry about that, forgot to push. Updated now.

2024-06-01 16:45 UTC, chadmroberts88 approved these changes

2024-06-01 16:45 UTC, chadmroberts88 commented
Approved @JordanWheelerDev!

2024-06-01 16:46 UTC, merged